-- =====================================================================
-- ESTATE360 — MVP DATABASE SCHEMA
-- Estate Visitor Access, Rent Tracking & Emergency Alert Hub
-- Target: Supabase (PostgreSQL 15+)
-- =====================================================================
-- Run this in the Supabase SQL Editor (or via `supabase db push`).
-- Idempotent-ish: safe to re-run on a fresh project. Drops nothing
-- destructively except objects it created itself (guarded by IF EXISTS).
-- =====================================================================

-- ---------------------------------------------------------------------
-- 0. EXTENSIONS
-- ---------------------------------------------------------------------
create extension if not exists "pgcrypto";   -- for gen_random_uuid()

-- ---------------------------------------------------------------------
-- 1. ENUM TYPES
-- ---------------------------------------------------------------------
do $$
begin
  if not exists (select 1 from pg_type where typname = 'user_role') then
    create type user_role as enum ('ADMIN', 'RESIDENT', 'SECURITY');
  end if;

  if not exists (select 1 from pg_type where typname = 'access_code_status') then
    create type access_code_status as enum ('ACTIVE', 'USED', 'EXPIRED', 'REVOKED');
  end if;

  if not exists (select 1 from pg_type where typname = 'alert_status') then
    create type alert_status as enum ('PENDING', 'RESOLVED');
  end if;
end $$;

-- ---------------------------------------------------------------------
-- 2. TABLE: units
-- ---------------------------------------------------------------------
create table if not exists public.units (
  id          uuid primary key default gen_random_uuid(),
  unit_number text not null unique,
  created_at  timestamptz not null default now()
);

comment on table public.units is 'Physical units/flats/houses within the estate.';

-- ---------------------------------------------------------------------
-- 3. TABLE: profiles
--    One row per auth.users row. role drives dashboard redirect.
-- ---------------------------------------------------------------------
create table if not exists public.profiles (
  id               uuid primary key references auth.users(id) on delete cascade,
  full_name        text not null,
  phone            text,
  role             user_role not null default 'RESIDENT',
  unit_id          uuid references public.units(id) on delete set null,
  rent_expiry_date date,               -- null for non-residents (admin/security)
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

comment on table public.profiles is 'Extends auth.users with role, unit assignment, and rent expiry.';
comment on column public.profiles.rent_expiry_date is 'Lease/rent expiry date; drives the countdown badge on /resident.';

create index if not exists idx_profiles_unit_id on public.profiles(unit_id);
create index if not exists idx_profiles_role     on public.profiles(role);

-- ---------------------------------------------------------------------
-- 4. TABLE: access_codes
--    6-char alphanumeric visitor pass codes (e.g. "B4K8M9" / displayed "B4K-8M9").
--    Charset excludes 0/O and 1/I to avoid visual ambiguity at the gate.
-- ---------------------------------------------------------------------
create table if not exists public.access_codes (
  id            uuid primary key default gen_random_uuid(),
  code          varchar(10) not null unique,   -- stored without dash, e.g. 'B4K8M9'
  visitor_name  text not null,
  visitor_phone text,
  resident_id   uuid not null references public.profiles(id) on delete cascade,
  unit_id       uuid not null references public.units(id) on delete cascade,
  status        access_code_status not null default 'ACTIVE',
  expires_at    timestamptz not null,
  created_at    timestamptz not null default now(),
  used_at       timestamptz,

  constraint chk_access_codes_code_charset
    check (code ~ '^[A-HJ-NP-Z2-9]{6,10}$')   -- excludes 0,O,1,I; uppercase only
);

comment on table public.access_codes is 'Visitor gate-pass codes generated by residents; validated by security.';

create index if not exists idx_access_codes_code        on public.access_codes(code);
create index if not exists idx_access_codes_resident_id  on public.access_codes(resident_id);
create index if not exists idx_access_codes_unit_id      on public.access_codes(unit_id);
create index if not exists idx_access_codes_status       on public.access_codes(status);
create index if not exists idx_access_codes_expires_at   on public.access_codes(expires_at);

-- ---------------------------------------------------------------------
-- 5. TABLE: emergency_alerts
--    Panic button events, broadcast in realtime to Security.
-- ---------------------------------------------------------------------
create table if not exists public.emergency_alerts (
  id          uuid primary key default gen_random_uuid(),
  unit_id     uuid not null references public.units(id) on delete cascade,
  resident_id uuid not null references public.profiles(id) on delete cascade,
  status      alert_status not null default 'PENDING',
  created_at  timestamptz not null default now(),
  resolved_at timestamptz
);

comment on table public.emergency_alerts is 'Panic-button emergency events triggered by residents.';

create index if not exists idx_emergency_alerts_status  on public.emergency_alerts(status);
create index if not exists idx_emergency_alerts_unit_id on public.emergency_alerts(unit_id);

-- ---------------------------------------------------------------------
-- 6. HELPER FUNCTIONS
-- ---------------------------------------------------------------------

-- 6a. Returns the calling user's role. SECURITY DEFINER + stable so it can
--     be used cheaply inside RLS policies without recursive RLS checks.
create or replace function public.current_user_role()
returns user_role
language sql
security definer
stable
set search_path = public
as $$
  select role from public.profiles where id = auth.uid();
$$;

-- 6b. Returns the calling user's unit_id.
create or replace function public.current_user_unit_id()
returns uuid
language sql
security definer
stable
set search_path = public
as $$
  select unit_id from public.profiles where id = auth.uid();
$$;

-- 6c. Auto-expire stale codes on read/validate. Called by the security
--     portal's validation RPC before checking status (see below).
create or replace function public.expire_stale_codes()
returns void
language sql
as $$
  update public.access_codes
  set status = 'EXPIRED'
  where status = 'ACTIVE' and expires_at < now();
$$;

-- 6d. Atomic validation RPC used by the Security portal.
--     Marks a valid code as USED and returns visitor + unit info in one
--     call, avoiding read-then-write races between guards.
create or replace function public.validate_access_code(p_code text)
returns table (
  result           text,               -- 'VALID' | 'USED' | 'EXPIRED' | 'INVALID' | 'REVOKED'
  visitor_name     text,
  visitor_phone    text,
  unit_number      text,
  resident_name    text,
  expires_at       timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.access_codes%rowtype;
begin
  perform public.expire_stale_codes();

  select * into v_row
  from public.access_codes
  where code = upper(regexp_replace(p_code, '[^A-Za-z0-9]', '', 'g'))
  limit 1;

  if not found then
    return query select 'INVALID', null::text, null::text, null::text, null::text, null::timestamptz;
    return;
  end if;

  if v_row.status = 'USED' then
    return query
      select 'USED', v_row.visitor_name, v_row.visitor_phone,
             u.unit_number, p.full_name, v_row.expires_at
      from public.units u, public.profiles p
      where u.id = v_row.unit_id and p.id = v_row.resident_id;
    return;
  elsif v_row.status = 'EXPIRED' or v_row.expires_at < now() then
    return query
      select 'EXPIRED', v_row.visitor_name, v_row.visitor_phone,
             u.unit_number, p.full_name, v_row.expires_at
      from public.units u, public.profiles p
      where u.id = v_row.unit_id and p.id = v_row.resident_id;
    return;
  elsif v_row.status = 'REVOKED' then
    return query select 'REVOKED', v_row.visitor_name, v_row.visitor_phone, null::text, null::text, v_row.expires_at;
    return;
  else
    -- ACTIVE and not expired -> mark USED, return VALID + details
    update public.access_codes
    set status = 'USED', used_at = now()
    where id = v_row.id;

    return query
      select 'VALID', v_row.visitor_name, v_row.visitor_phone,
             u.unit_number, p.full_name, v_row.expires_at
      from public.units u, public.profiles p
      where u.id = v_row.unit_id and p.id = v_row.resident_id;
    return;
  end if;
end;
$$;

grant execute on function public.validate_access_code(text) to authenticated;

-- 6e. Auto-update updated_at on profiles.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

-- 6f. Auto-create a profile row when a new auth.users row appears.
--     Role/unit default to RESIDENT/null; app updates them right after
--     sign-up (see /register flow), or an admin assigns them later.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', 'New User'),
    coalesce((new.raw_user_meta_data->>'role')::user_role, 'RESIDENT')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists trg_on_auth_user_created on auth.users;
create trigger trg_on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------------
-- 7. ROW LEVEL SECURITY
-- ---------------------------------------------------------------------
alter table public.units             enable row level security;
alter table public.profiles          enable row level security;
alter table public.access_codes      enable row level security;
alter table public.emergency_alerts  enable row level security;

-- ===== units =====
drop policy if exists "units_select_all_authenticated" on public.units;
create policy "units_select_all_authenticated"
  on public.units for select
  to authenticated
  using (true);   -- everyone signed-in can see the unit list (e.g. /register dropdown)

drop policy if exists "units_admin_write" on public.units;
create policy "units_admin_write"
  on public.units for all
  to authenticated
  using (public.current_user_role() = 'ADMIN')
  with check (public.current_user_role() = 'ADMIN');

-- ===== profiles =====
drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
  on public.profiles for select
  to authenticated
  using (id = auth.uid());

drop policy if exists "profiles_select_admin_all" on public.profiles;
create policy "profiles_select_admin_all"
  on public.profiles for select
  to authenticated
  using (public.current_user_role() = 'ADMIN');

drop policy if exists "profiles_select_security_residents" on public.profiles;
create policy "profiles_select_security_residents"
  on public.profiles for select
  to authenticated
  using (public.current_user_role() = 'SECURITY');
  -- security guards need to see resident names/units to respond to alerts

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
  on public.profiles for update
  to authenticated
  using (id = auth.uid())
  with check (id = auth.uid() and role = (select role from public.profiles where id = auth.uid()));
  -- residents can edit their own name/phone but NOT self-promote role

drop policy if exists "profiles_admin_write_all" on public.profiles;
create policy "profiles_admin_write_all"
  on public.profiles for all
  to authenticated
  using (public.current_user_role() = 'ADMIN')
  with check (public.current_user_role() = 'ADMIN');

drop policy if exists "profiles_insert_self" on public.profiles;
create policy "profiles_insert_self"
  on public.profiles for insert
  to authenticated
  with check (id = auth.uid());

-- ===== access_codes =====
drop policy if exists "access_codes_resident_select_own" on public.access_codes;
create policy "access_codes_resident_select_own"
  on public.access_codes for select
  to authenticated
  using (resident_id = auth.uid());

drop policy if exists "access_codes_resident_insert_own" on public.access_codes;
create policy "access_codes_resident_insert_own"
  on public.access_codes for insert
  to authenticated
  with check (
    resident_id = auth.uid()
    and unit_id = public.current_user_unit_id()
    and public.current_user_role() = 'RESIDENT'
  );

drop policy if exists "access_codes_resident_update_own" on public.access_codes;
create policy "access_codes_resident_update_own"
  on public.access_codes for update
  to authenticated
  using (resident_id = auth.uid())
  with check (resident_id = auth.uid());
  -- allows residents to REVOKE their own active codes

drop policy if exists "access_codes_security_select_all" on public.access_codes;
create policy "access_codes_security_select_all"
  on public.access_codes for select
  to authenticated
  using (public.current_user_role() = 'SECURITY');
  -- guards can look up any code for manual audit (validation itself goes through the RPC)

drop policy if exists "access_codes_admin_all" on public.access_codes;
create policy "access_codes_admin_all"
  on public.access_codes for all
  to authenticated
  using (public.current_user_role() = 'ADMIN')
  with check (public.current_user_role() = 'ADMIN');

-- ===== emergency_alerts =====
drop policy if exists "alerts_resident_select_own" on public.emergency_alerts;
create policy "alerts_resident_select_own"
  on public.emergency_alerts for select
  to authenticated
  using (resident_id = auth.uid());

drop policy if exists "alerts_resident_insert_own" on public.emergency_alerts;
create policy "alerts_resident_insert_own"
  on public.emergency_alerts for insert
  to authenticated
  with check (
    resident_id = auth.uid()
    and unit_id = public.current_user_unit_id()
    and public.current_user_role() = 'RESIDENT'
  );

drop policy if exists "alerts_security_select_all" on public.emergency_alerts;
create policy "alerts_security_select_all"
  on public.emergency_alerts for select
  to authenticated
  using (public.current_user_role() = 'SECURITY');

drop policy if exists "alerts_security_update_resolve" on public.emergency_alerts;
create policy "alerts_security_update_resolve"
  on public.emergency_alerts for update
  to authenticated
  using (public.current_user_role() = 'SECURITY')
  with check (public.current_user_role() = 'SECURITY');

drop policy if exists "alerts_admin_all" on public.emergency_alerts;
create policy "alerts_admin_all"
  on public.emergency_alerts for all
  to authenticated
  using (public.current_user_role() = 'ADMIN')
  with check (public.current_user_role() = 'ADMIN');

-- ---------------------------------------------------------------------
-- 8. REALTIME
--    Enable realtime replication for emergency_alerts (panic popups) and
--    access_codes (live status updates on the resident's code list).
-- ---------------------------------------------------------------------
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and tablename = 'emergency_alerts'
  ) then
    alter publication supabase_realtime add table public.emergency_alerts;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and tablename = 'access_codes'
  ) then
    alter publication supabase_realtime add table public.access_codes;
  end if;
end $$;

-- =====================================================================
-- END OF SCHEMA
-- =====================================================================
